service: lambda-example-service

provider:
  name: aws
  runtime: nodejs10.x
  region: ${env:AWS_REGION}

package:
  include:
    - handler.js
  exclude:
    - ./**

functions:
  hello:
    handler: handler.hello
